pipeline {
    agent any
    environment {
        // Define any necessary environment variables here
    }
    stages {
        stage('Checkout SCM') {
            steps {
                echo 'Checking out the repository'
                checkout scm
            }
        }

        stage('Clean Workspace') {
            steps {
                echo 'Cleaning workspace'
                deleteDir() // Clean the workspace before building
            }
        }

        stage('Clone Repository') {
            steps {
                echo 'Cloning the repository'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Building the project'
                script {
                    // Run the build.sh script from the correct path
                    sh './jenkins/scripts/build.sh'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying the project'
                script {
                    // Run the deploy.sh script from the correct path
                    sh './jenkins/scripts/deploy.sh'
                }
            }
        }
    }
    post {
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
