pipeline {
    agent any

    environment {
        IMAGE_TAG = 'latest' // You can change this if you need versioning
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Build Docker Images') {
            steps {
                script {
                    // Run build.sh to build the backend and frontend Docker images
                    sh './scripts/build.sh'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Run deploy.sh to deploy the app using Docker Compose
                    sh './scripts/deploy.sh'
                }
            }
        }

        stage('Post Actions') {
            steps {
                echo 'Pipeline succeeded!'
            }
        }
    }

    post {
        success {
            echo "Deployment succeeded!"
        }
        failure {
            echo "Deployment failed!"
        }
    }
}
